/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.floodlert;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author johnm
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_Username = new javax.swing.JLabel();
        jLabel1_Password = new javax.swing.JLabel();
        jPasswordField1_Password = new javax.swing.JPasswordField();
        jButton1_CreateAccount = new javax.swing.JButton();
        jButton1_ReturnToLogIn = new javax.swing.JButton();
        jPasswordField1_Password1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1_Username.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1_Username.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Username.setText("Username");
        getContentPane().add(jLabel1_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel1_Password.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1_Password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Password.setText("Password");
        getContentPane().add(jLabel1_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 22));

        jPasswordField1_Password.setBackground(new java.awt.Color(33, 55, 74));
        jPasswordField1_Password.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPasswordField1_Password.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1_Password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 70, 85), 1, true));
        getContentPane().add(jPasswordField1_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 249, -1));

        jButton1_CreateAccount.setBackground(new java.awt.Color(72, 140, 210));
        jButton1_CreateAccount.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton1_CreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_CreateAccount.setText("Create Account");
        jButton1_CreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_CreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_CreateAccountActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_CreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 50));

        jButton1_ReturnToLogIn.setBackground(new java.awt.Color(72, 140, 210));
        jButton1_ReturnToLogIn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton1_ReturnToLogIn.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_ReturnToLogIn.setText("Return to Log In");
        jButton1_ReturnToLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_ReturnToLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_ReturnToLogInActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_ReturnToLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 120, 50));

        jPasswordField1_Password1.setBackground(new java.awt.Color(33, 55, 74));
        jPasswordField1_Password1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPasswordField1_Password1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1_Password1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 70, 85), 1, true));
        getContentPane().add(jPasswordField1_Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 249, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/floodlert/create account.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnToMainMenu (){
        LogIn.main(null);
        this.dispose();
    }
    
    private void jButton1_ReturnToLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_ReturnToLogInActionPerformed
        // TODO add your handling code here:
        returnToMainMenu();
    }//GEN-LAST:event_jButton1_ReturnToLogInActionPerformed

    private void jButton1_CreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_CreateAccountActionPerformed
        // This creates a new account data on the database.
        // NOTE: If the username already exists in the database, the account will not be created.
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/floodlert","root","");
            String sql = "insert into login values (?,?)";
            
            PreparedStatement psmt = conn.prepareStatement(sql);
           
            psmt.setString(1, jPasswordField1_Password1.getText());
            psmt.setString(2, jPasswordField1_Password.getText());
         
            psmt.executeUpdate();
            
            sql = "insert into login_weather value ( ?, ? )";
            
            psmt = conn.prepareStatement(sql);
            
            psmt.setString(1, jPasswordField1_Password1.getText());
            psmt.setString(2, "Manila");
            
            psmt.executeUpdate();
            returnToMainMenu();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Login already Exist");
        }
    }//GEN-LAST:event_jButton1_CreateAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {        
            FlatArcDarkIJTheme.setup();
        } catch( Exception ex ) {
        System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_CreateAccount;
    private javax.swing.JButton jButton1_ReturnToLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Password;
    private javax.swing.JLabel jLabel1_Username;
    private javax.swing.JPasswordField jPasswordField1_Password;
    private javax.swing.JTextField jPasswordField1_Password1;
    // End of variables declaration//GEN-END:variables
}
