/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.floodlert;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author johnm
 */
public class LogIn extends javax.swing.JFrame {

    public static String username;
    
    public LogIn() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_Username = new javax.swing.JLabel();
        jTextField1_Username = new javax.swing.JTextField();
        jLabel1_Password = new javax.swing.JLabel();
        jPasswordField1_Password = new javax.swing.JPasswordField();
        jButton1_LogIn = new javax.swing.JButton();
        jLabel1_NewToFloodlert = new javax.swing.JLabel();
        jToggleButton1_CreateAccount = new javax.swing.JToggleButton();
        jLabel1_NewToFloodlert1 = new javax.swing.JLabel();
        Forgot_Password = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(24, 43, 60));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1_Username.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1_Username.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Username.setText("Username");
        getContentPane().add(jLabel1_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 20));

        jTextField1_Username.setBackground(new java.awt.Color(33, 55, 74));
        jTextField1_Username.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField1_Username.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1_Username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 70, 85), 1, true));
        getContentPane().add(jTextField1_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 190, -1));

        jLabel1_Password.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1_Password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Password.setText("Password");
        getContentPane().add(jLabel1_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 60, 20));

        jPasswordField1_Password.setBackground(new java.awt.Color(33, 55, 74));
        jPasswordField1_Password.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPasswordField1_Password.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1_Password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 70, 85), 1, true));
        getContentPane().add(jPasswordField1_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, -1));

        jButton1_LogIn.setBackground(new java.awt.Color(72, 140, 210));
        jButton1_LogIn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton1_LogIn.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_LogIn.setText("Log In");
        jButton1_LogIn.setBorder(null);
        jButton1_LogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_LogInActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 110, 20));

        jLabel1_NewToFloodlert.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1_NewToFloodlert.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_NewToFloodlert.setText("Forgot your password?");
        jLabel1_NewToFloodlert.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1_NewToFloodlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 120, 30));

        jToggleButton1_CreateAccount.setBackground(new java.awt.Color(72, 140, 210));
        jToggleButton1_CreateAccount.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jToggleButton1_CreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1_CreateAccount.setText("Create Account");
        jToggleButton1_CreateAccount.setBorder(null);
        jToggleButton1_CreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1_CreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1_CreateAccountActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1_CreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 110, 20));

        jLabel1_NewToFloodlert1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1_NewToFloodlert1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_NewToFloodlert1.setText("New to Floodlert?");
        jLabel1_NewToFloodlert1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1_NewToFloodlert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 30));

        Forgot_Password.setBackground(new java.awt.Color(72, 140, 210));
        Forgot_Password.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        Forgot_Password.setForeground(new java.awt.Color(255, 255, 255));
        Forgot_Password.setText("Reset Password");
        Forgot_Password.setBorder(null);
        Forgot_Password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Forgot_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Forgot_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Forgot_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 110, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/floodlert/sign in.png"))); // NOI18N
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1_CreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1_CreateAccountActionPerformed
       // TODO add your handling code here:
       CreateAccount.main(null); // goes to the create account window
       this.dispose();
    }//GEN-LAST:event_jToggleButton1_CreateAccountActionPerformed

    private void jButton1_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_LogInActionPerformed
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/floodlert","root","");
            String sql = "select * from login where username=? and password=?";
            
            PreparedStatement psmt = conn.prepareStatement(sql);
            
            psmt.setString(1, jTextField1_Username.getText());
            psmt.setString(2, jPasswordField1_Password.getText());
            
            ResultSet rs = psmt.executeQuery();
            
            if(rs.next() == true) // if password is correct
            {
                FloodLert.username = jTextField1_Username.getText();
                FloodLert.LogInPrompt();
                Dashboard.main(null);
                this.dispose();
            }
            else // if password is incorrect
            {
                JOptionPane.showMessageDialog(null, "Login Does Not Exist");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1_LogInActionPerformed

    private void Forgot_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Forgot_PasswordActionPerformed
       ForgotPass.main(null);
       this.dispose();
    }//GEN-LAST:event_Forgot_PasswordActionPerformed
        
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {        
            FlatArcDarkIJTheme.setup(); //(default code) UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch( Exception ex ) {
        System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>
        
        FloodLert.access = false;
        WeatherAPI.current_area = "";
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Forgot_Password;
    private javax.swing.JButton jButton1_LogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_NewToFloodlert;
    private javax.swing.JLabel jLabel1_NewToFloodlert1;
    private javax.swing.JLabel jLabel1_Password;
    private javax.swing.JLabel jLabel1_Username;
    private javax.swing.JPasswordField jPasswordField1_Password;
    private javax.swing.JTextField jTextField1_Username;
    private javax.swing.JToggleButton jToggleButton1_CreateAccount;
    // End of variables declaration//GEN-END:variables
}
