/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.floodlert;

import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author johnm
 */
public class ReportFlood extends javax.swing.JFrame {

    /**
     * Creates new form ReportFlood
     */
    public ReportFlood() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_Where = new javax.swing.JLabel();
        jComboBox1_City = new javax.swing.JComboBox<>();
        jLabel1_WhatIsTheHeight = new javax.swing.JLabel();
        jSlider1_FloodLevel = new javax.swing.JSlider();
        jLabel1_Low = new javax.swing.JLabel();
        jLabel1_Hight = new javax.swing.JLabel();
        jButton1_SubmitReport = new javax.swing.JButton();
        jButton1_Cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1_Where.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1_Where.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Where.setText("Where does the flood take place?");
        getContentPane().add(jLabel1_Where, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 199, 22));

        jComboBox1_City.setBackground(new java.awt.Color(33, 55, 74));
        jComboBox1_City.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jComboBox1_City.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1_City.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT CITY", "Alaminos", "Angeles City", "Antipolo", "Bacolod", "Bacoor", "Bago", "Baguio", "Bais", "Balanga", "Batac", "Batangas City", "Bayawan", "Baybay", "Bayugan", "Biñan", "Bislig", "Bogo", "Borongan", "Butuaan", "Cadbadbaran", "Cabanatuan", "Cabuyao", "Cadiz", "Cagayan de Oro", "Calaca", "Calamba", "Calapan", "Calbayog", "Caloocan", "Candon", "Canlaon", "Carcar", "Catbalogan", "Cauayan", "Cavite City", "Ceby City", "Cotabato City", "Dagupan", "Danao", "Dapitan", "Dasmariñas", "Davao City", "Digos", "Dipolog", "Dumaguete", "El Salvador", "Escalante", "Gapan", "General Santos", "General Trias", "Gingoog", "Guihulngan", "Himamaylan", "Ilagan", "Iligan", "Iloilo City", "Imus", "Iriga", "Isabela", "Kabankalan", "Kidapawan", "Koronadal", "La Carlota", "Lamitan", "Laoag", "Lapu-Lapu City", "Las Piñas", "Legazpi", "Ligao", "Lipa", "Lucena", "Maasin", "Mabalacat", "Makati", "Malabon", "Malaybalay", "Malolos", "Mandaluyong", "Mandaue", "Manila", "Marawi", "Marikina", "Masbate City", "Mati", "Mecauayan", "Muñoz", "Muntinlupa", "Naga (Camarines Sur)", "Naga (Cebu)", "Navotas", "Olongapo", "Ormoc", "Oroquieta", "Ozamiz", "Pagadian", "Palayan", "Panabo", "Parañaque", "Pasay", "Pasig", "Passi", "Puerto Princessa", "Quezon City", "Roxas", "Sagay", "Samal", "San Carlos (Negros Occidental)", "San Carlos (Pangasinan)", "San Fernando (La Union)", "San Fernando (Pampanga)", "San Jose", "San Jose del Monte", "San Juan", "San Pablo", "San Pedro", "Santa Rosa", "Santo Tomas", "Santiago", "Silay", "Sipalay", "Sorsogon City", "Surigao City", "Tabaco", "Tabuk", "Tacloban", "Tacurong", "Tagaytay", "Tagbilaran", "Taguig", "Tagum", "Talisay (Cebu)", "Talisay (Negros Occidental)", "Tanauan", "Tandag", "Tangub", "Tanjay", "Tarlac City", "Tayabas", "Toledo", "Trece Martires", "Tuguegarao", "Urdaneta", "Valencia", "Valenzuela", "Victoras", "Vigan", "Zamboanga City" }));
        jComboBox1_City.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 70, 85), 1, true));
        jComboBox1_City.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1_City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_CityActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1_City, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 220, -1));

        jLabel1_WhatIsTheHeight.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_WhatIsTheHeight.setText("How high is the flood?");
        getContentPane().add(jLabel1_WhatIsTheHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 314, 22));

        jSlider1_FloodLevel.setBackground(new java.awt.Color(52, 70, 85));
        jSlider1_FloodLevel.setMajorTickSpacing(1);
        jSlider1_FloodLevel.setMaximum(3);
        jSlider1_FloodLevel.setMinimum(1);
        jSlider1_FloodLevel.setPaintTicks(true);
        jSlider1_FloodLevel.setSnapToTicks(true);
        jSlider1_FloodLevel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jSlider1_FloodLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 137, -1));

        jLabel1_Low.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1_Low.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Low.setText("Low");
        getContentPane().add(jLabel1_Low, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 22));

        jLabel1_Hight.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1_Hight.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Hight.setText("High");
        getContentPane().add(jLabel1_Hight, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, 22));

        jButton1_SubmitReport.setBackground(new java.awt.Color(72, 140, 210));
        jButton1_SubmitReport.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_SubmitReport.setText("Submit Report");
        jButton1_SubmitReport.setBorder(null);
        jButton1_SubmitReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_SubmitReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_SubmitReportActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_SubmitReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 160, 20));

        jButton1_Cancel.setBackground(new java.awt.Color(72, 140, 210));
        jButton1_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_Cancel.setText("Cancel");
        jButton1_Cancel.setBorder(null);
        jButton1_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_CancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 80, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/floodlert/floodreport.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_CancelActionPerformed
        // Goes to Dashboard.java
        this.dispose();
    }//GEN-LAST:event_jButton1_CancelActionPerformed

    private void jButton1_SubmitReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_SubmitReportActionPerformed
        // Creates a new flood report data in the database.
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/floodlert","root","");
            String sql = "insert into floodReport values (?,?,?)"; 
            
            PreparedStatement psmt = conn.prepareStatement(sql);
           
            psmt.setString(1, jComboBox1_City.getSelectedItem().toString());
            psmt.setInt(2, jSlider1_FloodLevel.getValue());
            psmt.setString(3, FloodLert.username);
            
            psmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Report Submitted!");
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1_SubmitReportActionPerformed

    private void jComboBox1_CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_CityActionPerformed
        // specifies the city
        System.out.println(jComboBox1_City.getSelectedItem());
    }//GEN-LAST:event_jComboBox1_CityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {        
        FlatArcDarkIJTheme.setup();
        } catch( Exception ex ) {
        System.err.println( "Failed to initialize LaF" );
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportFlood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Cancel;
    private javax.swing.JButton jButton1_SubmitReport;
    private javax.swing.JComboBox<String> jComboBox1_City;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Hight;
    private javax.swing.JLabel jLabel1_Low;
    private javax.swing.JLabel jLabel1_WhatIsTheHeight;
    private javax.swing.JLabel jLabel1_Where;
    private javax.swing.JSlider jSlider1_FloodLevel;
    // End of variables declaration//GEN-END:variables
}
