/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.floodlert;

import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;

/**
 *
 * @author Josh Garcia
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChangeLocation = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Password = new javax.swing.JButton();
        jButton1_LogOut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChangeLocation.setBackground(new java.awt.Color(72, 140, 210));
        ChangeLocation.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ChangeLocation.setForeground(new java.awt.Color(255, 255, 255));
        ChangeLocation.setText("Change Location");
        ChangeLocation.setBorder(null);
        ChangeLocation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChangeLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeLocationActionPerformed(evt);
            }
        });
        getContentPane().add(ChangeLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 160, 20));

        jButton4.setBackground(new java.awt.Color(72, 140, 210));
        jButton4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 80, 30));

        Delete.setBackground(new java.awt.Color(72, 140, 210));
        Delete.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.setBorder(null);
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 160, 20));

        Password.setBackground(new java.awt.Color(72, 140, 210));
        Password.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Change Password");
        Password.setBorder(null);
        Password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 160, 20));

        jButton1_LogOut.setBackground(new java.awt.Color(72, 140, 210));
        jButton1_LogOut.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton1_LogOut.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_LogOut.setText("Log Out");
        jButton1_LogOut.setBorder(null);
        jButton1_LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 160, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/floodlert/settingss.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        this.dispose();
        DeleteAcc.main(null);// TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    Dashboard.main(null);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        this.dispose();
        ChangePassword.main(null);   
    }//GEN-LAST:event_PasswordActionPerformed

    private void ChangeLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeLocationActionPerformed
        this.dispose();
        ChangeLoc.main(null);           
    }//GEN-LAST:event_ChangeLocationActionPerformed

    private void jButton1_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_LogOutActionPerformed
        // goes to LogIn.java; also resets the logged in username to "null"
        FloodLert.username = null;
        FloodLert.LogInPrompt();
        LogIn.main(null);
        this.dispose();
    }//GEN-LAST:event_jButton1_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {        
        FlatArcDarkIJTheme.setup();
        } catch( Exception ex ) {
        System.err.println( "Failed to initialize LaF" );
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeLocation;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Password;
    private javax.swing.JButton jButton1_LogOut;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
