/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.floodlert;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.ImageIcon;


public class Dashboard extends javax.swing.JFrame {
    
    static void openResultsForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel1.setText("Welcome, " +  FloodLert.username + "!");
        
        WeatherAPI.fetch(WeatherAPI.currentUserArea());
        
        WeatherAPI.setValues();
        DateTime.setValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        basicforecast_box = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        temp = new javax.swing.JLabel();
        localdate = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        localtime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        searchbutton = new javax.swing.JButton();
        searchbar = new javax.swing.JTextField();
        settings = new javax.swing.JButton();
        tabbed_content = new javax.swing.JTabbedPane();
        weather_box = new javax.swing.JPanel();
        jPanel1_FloodLevel = new javax.swing.JPanel();
        jComboBox1_CitySelect = new javax.swing.JComboBox<>();
        jLabel1_FloodLevel = new javax.swing.JLabel();
        jLabel1_FloodLevelData = new javax.swing.JLabel();
        jButton1_SubmitFloodReport = new javax.swing.JButton();
        typhoon_box = new javax.swing.JPanel();
        jPanel1_FloodLevel2 = new javax.swing.JPanel();
        jComboBox1_RiverSelect = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel1_RiverReportPicture = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        basicforecast_box.setBackground(new java.awt.Color(51, 51, 51));
        basicforecast_box.setForeground(new java.awt.Color(51, 51, 51));
        basicforecast_box.setFocusable(false);

        status.setBackground(new java.awt.Color(237, 249, 244));
        status.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        status.setForeground(new java.awt.Color(237, 249, 244));
        status.setText("XXXXXX XXXXXX");

        temp.setBackground(new java.awt.Color(237, 249, 244));
        temp.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        temp.setForeground(new java.awt.Color(237, 249, 244));
        temp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        temp.setText("XX°");

        localdate.setBackground(new java.awt.Color(237, 249, 244));
        localdate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        localdate.setForeground(new java.awt.Color(237, 249, 244));
        localdate.setText("XX/XX/XXXX");

        location.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        location.setForeground(new java.awt.Color(237, 249, 244));
        location.setText("XXXXXXXXXXX, XXXXXXXXXXX");

        javax.swing.GroupLayout basicforecast_boxLayout = new javax.swing.GroupLayout(basicforecast_box);
        basicforecast_box.setLayout(basicforecast_boxLayout);
        basicforecast_boxLayout.setHorizontalGroup(
            basicforecast_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicforecast_boxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basicforecast_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(localdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(location, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        basicforecast_boxLayout.setVerticalGroup(
            basicforecast_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicforecast_boxLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(basicforecast_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(basicforecast_boxLayout.createSequentialGroup()
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(location)
                        .addGap(8, 8, 8)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        localtime.setBackground(new java.awt.Color(237, 249, 244));
        localtime.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        localtime.setForeground(new java.awt.Color(237, 249, 244));
        localtime.setText("XX:XX XX");

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N

        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });

        settings.setText("Settings");
        settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });

        tabbed_content.setBackground(new java.awt.Color(0, 0, 0));
        tabbed_content.setForeground(new java.awt.Color(255, 255, 255));
        tabbed_content.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabbed_content.setPreferredSize(new java.awt.Dimension(920, 540));

        weather_box.setBackground(new java.awt.Color(0, 0, 0));
        weather_box.setForeground(new java.awt.Color(255, 255, 255));
        weather_box.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        weather_box.setPreferredSize(new java.awt.Dimension(918, 507));

        jPanel1_FloodLevel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox1_CitySelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT CITY", "Alaminos", "Angeles City", "Antipolo", "Bacolod", "Bacoor", "Bago", "Baguio", "Bais", "Balanga", "Batac", "Batangas City", "Bayawan", "Baybay", "Bayugan", "Biñan", "Bislig", "Bogo", "Borongan", "Butuaan", "Cadbadbaran", "Cabanatuan", "Cabuyao", "Cadiz", "Cagayan de Oro", "Calaca", "Calamba", "Calapan", "Calbayog", "Caloocan", "Candon", "Canlaon", "Carcar", "Catbalogan", "Cauayan", "Cavite City", "Ceby City", "Cotabato City", "Dagupan", "Danao", "Dapitan", "Dasmariñas", "Davao City", "Digos", "Dipolog", "Dumaguete", "El Salvador", "Escalante", "Gapan", "General Santos", "General Trias", "Gingoog", "Guihulngan", "Himamaylan", "Ilagan", "Iligan", "Iloilo City", "Imus", "Iriga", "Isabela", "Kabankalan", "Kidapawan", "Koronadal", "La Carlota", "Lamitan", "Laoag", "Lapu-Lapu City", "Las Piñas", "Legazpi", "Ligao", "Lipa", "Lucena", "Maasin", "Mabalacat", "Makati", "Malabon", "Malaybalay", "Malolos", "Mandaluyong", "Mandaue", "Manila", "Marawi", "Marikina", "Masbate City", "Mati", "Mecauayan", "Muñoz", "Muntinlupa", "Naga (Camarines Sur)", "Naga (Cebu)", "Navotas", "Olongapo", "Ormoc", "Oroquieta", "Ozamiz", "Pagadian", "Palayan", "Panabo", "Parañaque", "Pasay", "Pasig", "Passi", "Puerto Princessa", "Quezon City", "Roxas", "Sagay", "Samal", "San Carlos (Negros Occidental)", "San Carlos (Pangasinan)", "San Fernando (La Union)", "San Fernando (Pampanga)", "San Jose", "San Jose del Monte", "San Juan", "San Pablo", "San Pedro", "Santa Rosa", "Santo Tomas", "Santiago", "Silay", "Sipalay", "Sorsogon City", "Surigao City", "Tabaco", "Tabuk", "Tacloban", "Tacurong", "Tagaytay", "Tagbilaran", "Taguig", "Tagum", "Talisay (Cebu)", "Talisay (Negros Occidental)", "Tanauan", "Tandag", "Tangub", "Tanjay", "Tarlac City", "Tayabas", "Toledo", "Trece Martires", "Tuguegarao", "Urdaneta", "Valencia", "Valenzuela", "Victoras", "Vigan", "Zamboanga City" }));
        jComboBox1_CitySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_CitySelectActionPerformed(evt);
            }
        });

        jLabel1_FloodLevel.setText("Flood Level:");

        jLabel1_FloodLevelData.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1_FloodLevelData.setText("[NO DATA]");
        jLabel1_FloodLevelData.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jButton1_SubmitFloodReport.setText("Submit Flood Report");
        jButton1_SubmitFloodReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_SubmitFloodReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_FloodLevelLayout = new javax.swing.GroupLayout(jPanel1_FloodLevel);
        jPanel1_FloodLevel.setLayout(jPanel1_FloodLevelLayout);
        jPanel1_FloodLevelLayout.setHorizontalGroup(
            jPanel1_FloodLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_FloodLevelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_FloodLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1_CitySelect, 0, 357, Short.MAX_VALUE)
                    .addGroup(jPanel1_FloodLevelLayout.createSequentialGroup()
                        .addGroup(jPanel1_FloodLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1_FloodLevel)
                            .addGroup(jPanel1_FloodLevelLayout.createSequentialGroup()
                                .addComponent(jLabel1_FloodLevelData, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1_SubmitFloodReport, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1_FloodLevelLayout.setVerticalGroup(
            jPanel1_FloodLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_FloodLevelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1_CitySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1_FloodLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1_FloodLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1_FloodLevelData, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_SubmitFloodReport))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout weather_boxLayout = new javax.swing.GroupLayout(weather_box);
        weather_box.setLayout(weather_boxLayout);
        weather_boxLayout.setHorizontalGroup(
            weather_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_FloodLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        weather_boxLayout.setVerticalGroup(
            weather_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_FloodLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbed_content.addTab("Flood Report", weather_box);

        typhoon_box.setBackground(new java.awt.Color(0, 0, 51));
        typhoon_box.setForeground(new java.awt.Color(0, 0, 0));
        typhoon_box.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        typhoon_box.setPreferredSize(new java.awt.Dimension(918, 507));

        jPanel1_FloodLevel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox1_RiverSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT RIVER", "Pampanga", "Agno", "Bicol", "Cagayan\t", "Pasig-Marikina (Metro Manila Flood Monitoring)\t", "Abra\t", "Cagayan De Oro\t", "Ilog-Hilabangan\t", "Jalaur\t", "Panay\t", "Tagum-Libuganon\t", "Abulog\t", "Agusan\t", "Agus\t", "Buayan-Malungon\t", "Davao", "Mindanao", "Tagoloan", "Angat Sub-basin", "Binga-Ambuklao-San Roque Sub-basin", "Pantabangan Sub-basin", "Magat Sub-basin" }));
        jComboBox1_RiverSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_RiverSelectActionPerformed(evt);
            }
        });

        jLabel1_RiverReportPicture.setText("Select a River");
        jScrollPane2.setViewportView(jLabel1_RiverReportPicture);

        javax.swing.GroupLayout jPanel1_FloodLevel2Layout = new javax.swing.GroupLayout(jPanel1_FloodLevel2);
        jPanel1_FloodLevel2.setLayout(jPanel1_FloodLevel2Layout);
        jPanel1_FloodLevel2Layout.setHorizontalGroup(
            jPanel1_FloodLevel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_FloodLevel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_FloodLevel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_FloodLevel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_FloodLevel2Layout.createSequentialGroup()
                        .addComponent(jComboBox1_RiverSelect, 0, 211, Short.MAX_VALUE)
                        .addGap(152, 152, 152))))
        );
        jPanel1_FloodLevel2Layout.setVerticalGroup(
            jPanel1_FloodLevel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_FloodLevel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1_RiverSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout typhoon_boxLayout = new javax.swing.GroupLayout(typhoon_box);
        typhoon_box.setLayout(typhoon_boxLayout);
        typhoon_boxLayout.setHorizontalGroup(
            typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_FloodLevel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        typhoon_boxLayout.setVerticalGroup(
            typhoon_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_FloodLevel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbed_content.addTab("River Basins", typhoon_box);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(tabbed_content, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(basicforecast_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchbutton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localtime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(settings))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(localtime)
                            .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(basicforecast_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabbed_content, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     public void searchProcess(String area) {
        if (area.equals("")) {
            WeatherAPI.current_area = "";
            WeatherAPI.fetch(WeatherAPI.currentUserArea());
        } else if (WeatherAPI.current_area != area){
            WeatherAPI.current_area = area;
            WeatherAPI.fetch(WeatherAPI.currentUserArea());
        }
        WeatherAPI.setValues();
    }
    
    private void jButton1_SubmitFloodReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_SubmitFloodReportActionPerformed
        // goes to ReportFlood.java
        ReportFlood.main(null);
    }//GEN-LAST:event_jButton1_SubmitFloodReportActionPerformed

    private void jComboBox1_CitySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_CitySelectActionPerformed
        // Upon selecting a city inside the combo box, it will accumulate the average of the total flood level based on the databse.
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/floodlert","root","");
            Statement psmt = conn.createStatement();
            String x= String.valueOf(jComboBox1_CitySelect.getSelectedItem());
            String sql =  
                "SELECT AVG(floodLevel) as level\n" +
                "FROM floodreport\n" +
                "WHERE city='"+x+"'";
            
        ResultSet res = psmt.executeQuery(sql);

        String flevel="";
        while (res.next()){
            flevel = res.getString("level");
        }
        
        // If there's no flood level data for that city, this will display instead.
        if (flevel == null){
            flevel = "[NO DATA]";
        }
        
        // displays the flood level on the dashboard
        jLabel1_FloodLevelData.setText(flevel);     
           
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jComboBox1_CitySelectActionPerformed
    public void searchbarKeyPressed(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            searchProcess(searchbar.getText());
        }
    }  
    
    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
    searchProcess(searchbar.getText());
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
        this.dispose();
        Settings.main(null);// TODO add your handling code here:
    }//GEN-LAST:event_settingsActionPerformed
    
    ImageIcon RiverReport_Pampanga = new ImageIcon("RiverReport_Pampanga.png");
    ImageIcon RiverReport_Agno = new ImageIcon("RiverReport_Agno.png");
    ImageIcon RiverReport_Bicol = new ImageIcon("RiverReport_Bicol.png");
    
    private void jComboBox1_RiverSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_RiverSelectActionPerformed
        // When you select a river on the combo box, a picture of the river report will appear below it.
        jLabel1_RiverReportPicture.setText(null); // removes the placeholder text by default
        String river = jComboBox1_RiverSelect.getSelectedItem().toString();
        switch(river){
            case "Pampanga":
                jLabel1_RiverReportPicture.setIcon(RiverReport_Pampanga);
                System.out.println("Pampanga");
                break;
            case "Agno":
                jLabel1_RiverReportPicture.setIcon(RiverReport_Agno);
                System.out.println("Agno");
                break;
            case "Bicol":
                jLabel1_RiverReportPicture.setIcon(RiverReport_Bicol);
                System.out.println("Bicol");
                break;
        }
    }//GEN-LAST:event_jComboBox1_RiverSelectActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {        
        FlatArcDarkIJTheme.setup();
        } catch( Exception ex ) {
        System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>
        
        FloodLert.access = true;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basicforecast_box;
    private javax.swing.JButton jButton1_SubmitFloodReport;
    private javax.swing.JComboBox<String> jComboBox1_CitySelect;
    private javax.swing.JComboBox<String> jComboBox1_RiverSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_FloodLevel;
    private javax.swing.JLabel jLabel1_FloodLevelData;
    private javax.swing.JLabel jLabel1_RiverReportPicture;
    private javax.swing.JPanel jPanel1_FloodLevel;
    private javax.swing.JPanel jPanel1_FloodLevel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    public static javax.swing.JLabel localdate;
    public static javax.swing.JLabel localtime;
    public static javax.swing.JLabel location;
    private javax.swing.JTextField searchbar;
    private javax.swing.JButton searchbutton;
    private javax.swing.JButton settings;
    public static javax.swing.JLabel status;
    private javax.swing.JTabbedPane tabbed_content;
    public static javax.swing.JLabel temp;
    private javax.swing.JPanel typhoon_box;
    private javax.swing.JPanel weather_box;
    // End of variables declaration//GEN-END:variables
}
